// Generated by Wrangler by running `wrangler types`

interface Env {
	AI: Ai;
	KITCHEN_DEVICE_ID: any;
	DINNING_DEVICE_ID: any;
	LIVINGROOM_DEVICE_ID: any;
	BEDROOM_DEVICE_ID: any;
	BASE_URL: string;
	ACCESS_KEY: string;
	SECRET_KEY: string;
	APP_API_KEY: string;
	OPENAI_API_KEY: string;
	OPENAI_API_URL: string
}
